"""
This function evaluates a batch of predictions by computing the (1) novelty, (2) validity,
(3) uniqueness, (4) Fréchet ChemNet distance, and (5) KL divergence for the final
root molecules which correspond to *unrecovered* molecules in all the generated trees.
"""
from tdc import Evaluator
import pandas as pd

kl_divergence = Evaluator(name = 'KL_Divergence')
fcd_distance = Evaluator(name = 'FCD_Distance')
novelty = Evaluator(name = 'Novelty')
validity = Evaluator(name = 'Validity')
uniqueness = Evaluator(name = 'Uniqueness')

if __name__ == '__main__':
    # load the final root molecules generated by a prediction run using a pre-trained model
    result_train = pd.read_csv('../results/decode_result_test_processed_property.csv.gz', compression='gzip')

    # get the unrecovered molecules only
    # result_test_unrecover = result_train[result_train['recovered sa'] != -1][result_train['similarity'] != 1.0]
    result_test_unrecover = result_train[result_train['recovered sa'] != -1]

    # compute the following properties, using the TDC
    print(f"Novelty: {novelty(result_test_unrecover['query SMILES'].tolist(), result_test_unrecover['decode SMILES'].tolist())}")
    print(f"Validity: {validity(result_test_unrecover['decode SMILES'].tolist())}")
    print(f"Uniqueness: {uniqueness(result_test_unrecover['decode SMILES'].tolist())}")
    print(f"FCD: {fcd_distance(result_test_unrecover['query SMILES'].tolist(), result_test_unrecover['decode SMILES'].tolist())}")
    print(f"KL: {kl_divergence(result_test_unrecover['query SMILES'].tolist()[:10000], result_test_unrecover['decode SMILES'].tolist()[:10000])}")
